version: "3.9"

services:
  Prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: Prometheus
    user: "1000:1000"
    env_file:
      - /volume1/docker/Prometheus/.env
    ports:
      - "9090:9090"
    volumes:
      - /volume1/docker/Prometheus/config:/etc/prometheus
      - /volume1/docker/Prometheus/data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=30d"
    networks:
      - metrics

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: Grafana
    user: "472"
    env_file:
      - /volume1/docker/Grafana/env
    ports:
      - "3000:3000"
    volumes:
      - /volume1/docker/Grafana/data:/var/lib/grafana
      - /volume1/docker/Grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - /volume1/docker/Grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - Prometheus
    networks:
      - metrics

  unpoller:
    image: ghcr.io/unpoller/unpoller:latest
    restart: unless-stopped
    container_name: Unpoller
    env_file:
      - /volume1/docker/Unpoller/.env
    ports:
      - "9130:9130"
    networks:
      - metrics

  dozzle:
    image: amir20/dozzle:latest
    restart: unless-stopped
    container_name: dozzle
    env_file:
      - /volume1/docker/dozzle/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"

networks:
  metrics:
    driver: bridge
